name: Build - master

on:
  # run when a pr is merged to master
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      AuthorName:
        description: 'Author name'
        required: true
        type: string
      AuthorEmail:
        description: 'Author email'
        required: true
        type: string
      AuthorMessage:
        description: 'Message'
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{github.run_number}}

    steps:
      - if: ${{ github.event.inputs.AuthorName  != '' }}
        run: |
          echo "::github.event.head_commit.author.name::${{ github.event.inputs.AuthorName }}"

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Print Info
        run: |
          echo "GITHUB_WORKFLOW      ${GITHUB_WORKFLOW}"
          echo github.event.head_commit.author.name is ${{ github.event.head_commit.author.name }}
          echo github.event.inputs is "${{ toJSON(github.event.inputs) }}"
          echo "GITHUB_RUN_ID        ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER    ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_ACTOR         ${GITHUB_ACTOR}"
          echo "GITHUB_SHA (commit)  ${GITHUB_SHA}"
          echo "GITHUB_REF           ${GITHUB_REF}"
          echo "BUILD_NUMBER         ${BUILD_NUMBER}"
          echo "BUILD_VERSION        ${BUILD_VERSION}"
          echo "DOCKER_IMAGE         ${DOCKER_IMAGE}"

  dispatch:
    needs: build
    strategy:
      matrix:
        repo: ['josel-sportsbet/cbb-test-environment']
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2

      - name: Notify Clients
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TEST_SECRET }}
          repository: ${{matrix.repo}}
          event-type: test-environment-publish
          client-payload: '{"image_manifest": {"ImageName": "${{env.DOCKER_IMAGE}}", "ImageTag": "${{env.BUILD_VERSION}}"}, "github": ${{ toJson(github) }}}'

